stages:
  - build
  - publish

.node: &node
  image: apextoaster/node:10.1
  tags:
    - platform:k8s
    - runner:shared
  allow_failure: false
  before_script:
    - echo "${NPM_SECRET}" | base64 -d > ${HOME}/.npmrc

build:
  <<: [*node]
  stage: build

  artifacts:
    expire_in: 1 week
    paths:
      - out/coverage
      - out/docs
      - out/main-bundle.*
      - out/version.json

  script:
    - yarn
    - make strict

publish:
  <<: [*node]
  stage: publish
  only:
    - tags

  dependencies:
    - build

  script:
    - npm publish